vnflcm:
  vnfInstanceName: pod56-sc1
  vnfProductName: Signaling_Controller
  vnfSoftwareVersion: 1.12.0+43
  values-file: values.yaml
  instantiate-file: instantiate.json
  evnfmName: pod56

access-info:
  oam: 10.130.34.244
  ldap-admin:
    user: admin
    pass: cm9vdHJvb3Q=
  users:
  - user: tsadm
    pass: VHNAZG01Z2NAYjF1ZXM=
    pass-init: dHNhZG0=
pipeline:
- module: create-namespace
- module: create-k8s-resource
  file: day0_secrets/bsf-db-secret.yaml
- module: create-k8s-resource
  file: day0_secrets/distributed_coordinator_ed_sc_secret.yaml
- module: create-k8s-resource
  file: day0_secrets/distributed_coordinator_ed_secret.yaml
- module: create-k8s-resource
  file: day0_secrets/ldap-secret.yaml
- module: create-k8s-resource
  file: day0_secrets/eric-sc-bragent-secret.yaml
- module: create-k8s-resource
  file: day0_secrets/wcdbcd-admin-secret.yaml
- module: create-k8s-resource
  file: day0_secrets/wcdbcd-day0-secret.yaml
- module: create-k8s-secret
  name: snmp-alarm-provider-config
  sources:
  - type: file
    key: config.json
    file: snmp-config.json
- module: instantiate
- module: verify-pod-running
  ignore-not-running:
  - eric-data-search-engine-curator
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: network-policy/eric-pm-server-allow.yaml
    file2: network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: Create pm server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-sc.ingress.pod56-eccd1.seln.ete.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: load-cmyp-user-config
  file: user-config.txt
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 30
- module: change-initial-password
- module: load-cmyp-app-config
  file: external-certificates.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: external-certificates-bsf.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: external-certificates-scp.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
# - module: load-cmyp-app-config
#   file: bsf-config.txt
#   user-id: 0
#   proto: ssh
#   retry-interval: 30
# - module: sleep
#   duration: 10
# - module: load-cmyp-app-config
#   file: scp-config.txt
#   user-id: 0
#   proto: ssh
#   retry-interval: 30
# - module: sleep
#   duration: 10
- module: load-cmyp-app-config
  file: ddc-config.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  name: Database initialize
  user-id: 0
  commands: |-
    bsf-function nf-instance bsf1 bsf-service serviceName1 binding-database initialize-db datacenter { name datacenter1 }
    end
- module: sleep
  duration: 10
