
---
apiVersion: v1
data:
  kcadminid: YWRtaW4=  # admin 
  kcpasswd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
  pguserid: YWRtaW4= # admin
  pgpasswd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
kind: Secret
metadata:
  name: eric-sec-access-mgmt-creds
  namespace: evnfm
type: Opaque

---
apiVersion: v1
data:
  custom-pwd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
  custom-user: ZW9fdXNlcg==
  metrics-pwd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
  metrics-user: ZXhwb3J0ZXI=
  replica-pwd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
  replica-user: cmVwbGljYQ==
  super-pwd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
  super-user: cG9zdGdyZXM=
kind: Secret
metadata:
  name: eric-eo-database-pg-secret
  namespace: evnfm
type: Opaque

---
apiVersion: v1
data:
  htpasswd: dm5mbTokMnkkMDUkSVdwZ1ppREt5THNJTlU2bzIvaEpnZTQ2Q2lmT1RhbVJIaU1ESHNwQkJZUGdiV2NLRW0vRXUK # htpasswd -cBb htpasswd vnfm 'Dm5GC@S0lut!on'
kind: Secret
metadata:
  name: container-registry-users-secret
  namespace: evnfm
type: Opaque

---
apiVersion: v1
data:
  url: ZG9ja2VyLXJlZ2lzdHJ5LmV2bmZtLnBvZDU2LWVjY2QyLnNlbG4uZXRlLmVyaWNzc29uLnNl # docker-registry.evnfm.pod56-eccd2.seln.ete.ericsson.se
  userid: dm5mbQ== # vnfm
  userpasswd: RG01R0NAUzBsdXQhb24= # Dm5GC@S0lut!on
kind: Secret
metadata:
  name: container-credentials
  namespace: evnfm
type: Opaque
