vnflcm:
  orchestrator: helm
  vnfInstanceName: vpod2-cces1
  vnfProductName: CCES
  vnfSoftwareVersion: 1.13.5+24
  values-file: values.yaml
  namespace: cces
  clusterName: n182-eccd2
  csar-file: /proj/pccc_builds/images/CCXX/CCES/CCES_1.13/CCES_1.13_PRG_T-152675/Ericsson.CCES.CXP9037720_1_13_5+24.csar
access-info:
  oam: cces1-n182-vpod2.seli.gic.ericsson.se
  ldap-admin:
    user: sysadmin
    pass: c3lzQWRtMW5ARGF5MA==
  users:
  - user: cces-admin
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
  - user: cces-sec
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
pipeline:
  # This module takes very long time so it is commented out for now. But this config has been verified for CCES.
#- module: push-images-to-registry
#  cleanup: true
#  remote-server:
#    host: n182-vpod1-cnis-cluster.seli.gic.ericsson.se
#    user: eccd
#    ssh-key: /lab/pccc_utils/scripts/ssh_key2/n182vpod1_key
#  tool:
#    cli: nerdctl
#  registry:
#     url: registry01.eoaas.n182.vpod1.seli.gic.ericsson.se
#     user: vnfm-user
#     pass: RGVmYXVsdFAxMjM0NSE=
#- module: install-crd
#  namespace: eric-crd-ns
#  registry:
#    host: registry01.eoaas.n182.vpod1.seli.gic.ericsson.se
#    username: vnfm-user
#    password: RGVmYXVsdFAxMjM0NSE=
#  pullSecret: regcred
#  additional-values:
#    eric-tm-ingress-controller-cr-crd:
#      rbac.create: true
- module: create-namespace
- module: run-k8s-command
  name: Create docker registry secret
  cmd: create secret docker-registry regcred --docker-server=registry01.eoaas.n182.vpod1.seli.gic.ericsson.se --docker-username=vnfm-user --docker-password=DefaultP12345!
- module: create-k8s-secret
  name: eric-sec-ldap-server-creds
  sources:
  - type: literal
    key: adminuser
    value: sysadmin
  - type: literal
    key: passwd
    value: sysAdm1n@Day0
  - type: literal
    key: adminpasswd
    value: $6$fzLPYlRZCpweJMJC$AiNfP0WYE3npY8Za6GxMFoGj75TOl.TS6tmnnky2Bv5wY0Ek8RIoJlr9pyj0LF3wMMaNsNTUH4jp2lIHviJGS0
- module: create-k8s-secret
  name: eric-data-distributed-coordinator-creds
  sources:
  - type: literal
    key: etcdpasswd
    value: sysAdm1n@Day0
- module: create-k8s-secret
  name: eric-sec-access-mgmt-creds
  sources:
  - type: literal
    key: kcadminid
    value: admin
  - type: literal
    key: kcpasswd
    value: sysAdm1n@Day0
- module: create-k8s-secret
  name: sftp-server-config
  sources:
  - type: file
    key: sftpConfig.json
    file: ../sftp-config.json
- module: instantiate
- module: verify-pod-running
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: ../network-policy/eric-pm-server-allow.yaml
    file2: ../network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: pm-server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-cces1.ingress.node182-cluster2.seli.gic.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: load-cmyp-user-config
  file: ../user-config.xml
  proto: netconf
  retry-interval: 30
- module: sleep
  duration: 30
- module: change-initial-password
- module: load-cmyp-app-config
  file: ../external-certificates.xml
  user-id: 1
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ../nef-config.xml
  proto: netconf
- module: sleep
  duration: 10
#- module: load-cmyp-app-config
#  file: ../nef-diameter-config.xml
#  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ../nrfagent-config.xml
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ../ddc-config.xml
  proto: netconf
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ../snmp-config.xml
  proto: netconf
- module: sleep
  duration: 60
- module: provision-nef
  host: prov-cces1-n182-vpod2.seli.gic.ericsson.se
  trustca: ../../../../certs/RootCA/ca.crt
  client-cert: ../../certificates/cces1/cces1-prov-client.crt
  client-key: ../../certificates/cces1/cces1-prov-client.key
  prov-info:
  - api-path: Provisioning/generic/entity/v2
    data-file: ../nef-provisioning/1_ServiceProvider.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: ../nef-provisioning/2_ServiceProviderServiceSubscription.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: ../nef-provisioning/3_Application.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/generic/entity/v2
    data-file: ../nef-provisioning/4_ApplicationServiceSubscription.xml
    method: POST
    headers:
      Content-Type: application/xml
      Accept: application/xml
  - api-path: Provisioning/qos/v1/information/QI_001
    data-file: ../nef-provisioning/5_QoS_information.json
    method: PUT
    headers:
      Content-Type: application/json
