#######################################################################################
## Configuration file of host configuration of servers                                #
#######################################################################################
## hostConfig: A list of Host Configurations each adapted to a certain type of Host.
## Additional host configurations can be created as per need basis for each specific
## system configuration. A certain Host Profile can be assigned to a specific host by
## refering to a Host Profile name from within the physicalHosts or virtualHosts keys
## (hosts.yaml).
##
## Attributes of the hostConfig key:
## - name: A human understandable name refering to the type of physical or virtual host
## the Host Configuration refers to.
## - lldp.enabled: Set to True for enabling of LLDP (Link Layer Discovery Protocol) on
## the host. False, that is, disabled as default.
## - lldp.msgTxInterval: Configurable between 1 and 3600 s with a default value of 30 s.
## See IEEE Std 802.1AB for more information.
## - lldp.msgTxHold: Configurable between 1 and 100 with a default value of 4. See
## IEEE Std 802.1AB for more information.
## - kernelBootParameters: Kernel boot parameters adapted for the certain host. Should
## normally not need to be changed.
## - sysctlOptions: Linux sysctl options for kernel parameter settings. Should
## normally not need to be changed.
---
hostConfig:
  - name: compute_host_config
    hardeningProfile: default
    cpuScalingGovernor: performance
    lldp:
      enabled: False
      msgTxInterval: 30
      msgTxHold: 4
    kernelBootParameters: audit=1 console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0 rootdelay=90 nomodeset crashkernel=256M transparent_hugepage=never intel_iommu=on iommu=pt nomdmonddf nomdmonisw plymouth.ignore-serial-consoles idle=halt
    sysctlOptions:
      - fs.aio-max-nr: 1048576
      - net.nf_conntrack_max: 1048576
      - kernel.panic: 60
      - kernel.printk: 1
      - kernel.nmi_watchdog: 0
      - kernel.sched_min_granularity_ns: 3000000
      - kernel.sched_wakeup_granularity_ns: 4000000
      - net.ipv4.ip_local_reserved_ports: 35357,41055-41056,49000-49001,49152-49215,55572,58882
      - vm.swappiness: 10
      - vm.stat_interval: 120
      - net.ipv4.conf.default.arp_accept: 1
      - net.core.netdev_max_backlog: 261144
      - net.ipv4.tcp_keepalive_intvl: 3
      - net.ipv4.tcp_keepalive_time: 30
      - net.ipv4.tcp_keepalive_probes: 8
      - net.ipv4.conf.all.arp_accept: 1
      - net.ipv4.tcp_retries2: 5
      - net.bridge.bridge-nf-call-arptables: 1
      - net.bridge.bridge-nf-call-iptables: 1
      - net.bridge.bridge-nf-call-ip6tables: 1
      - net.ipv4.neigh.default.gc_thresh1: 4096
      - net.ipv4.neigh.default.gc_thresh2: 8192
      - net.ipv4.neigh.default.gc_thresh3: 16384
      - net.ipv6.neigh.default.gc_thresh1: 4096
      - net.ipv6.neigh.default.gc_thresh2: 8192
      - net.ipv6.neigh.default.gc_thresh3: 16384
      - net.ipv4.ip_forward: 1
      - net.ipv4.conf.all.arp_filter: 1
      - net.ipv4.conf.all.arp_announce: 2
      - net.ipv4.conf.all.arp_notify: 1
      - net.ipv4.conf.default.log_martians: 0
      - net.ipv4.conf.all.secure_redirects: 0
      - net.ipv4.conf.all.rp_filter: 1
      - net.ipv4.conf.all.accept_source_route: 0
      - net.ipv4.conf.default.secure_redirects: 0
      - net.ipv4.conf.all.accept_redirects: 0
      - net.ipv4.conf.default.rp_filter: 1
      - net.ipv4.conf.default.accept_source_route: 0
      - net.ipv4.conf.default.accept_redirects: 0
      - net.ipv4.conf.all.log_martians: 0
      - net.ipv6.conf.default.disable_ipv6: 0
      - net.ipv6.conf.all.disable_ipv6: 0
      - net.ipv6.conf.all.accept_redirects: 0
      - net.ipv6.conf.default.accept_redirects: 0
      - vm.max_map_count: 262144
      - net.ipv4.ip_nonlocal_bind: 1
      - net.ipv6.ip_nonlocal_bind: 1
      - net.unix.max_dgram_qlen: 128
      - net.ipv6.conf.default.forwarding: 1
      - net.ipv6.conf.all.forwarding: 1
      - kernel.numa_balancing: 0
  - name: compute_realtime_host_config
    hardeningProfile: default
    cpuScalingGovernor: performance
    lldp:
      enabled: False
      msgTxInterval: 30
      msgTxHold: 4
    kernel: kernel-rt
    kernelBootParameters: audit=1 console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0 rootdelay=90 nomodeset crashkernel=256M transparent_hugepage=never intel_iommu=on iommu=pt nomdmonddf nomdmonisw plymouth.ignore-serial-consoles idle=halt
    sysctlOptions:
      - fs.aio-max-nr: 1048576
      - net.nf_conntrack_max: 1048576
      - kernel.panic: 60
      - kernel.printk: 1
      - kernel.nmi_watchdog: 0
      - kernel.sched_min_granularity_ns: 3000000
      - kernel.sched_wakeup_granularity_ns: 4000000
      - net.ipv4.ip_local_reserved_ports: 35357,41055-41056,49000-49001,49152-49215,55572,58882
      - vm.swappiness: 10
      - vm.stat_interval: 120
      - net.ipv4.conf.default.arp_accept: 1
      - net.core.netdev_max_backlog: 261144
      - net.ipv4.tcp_keepalive_intvl: 3
      - net.ipv4.tcp_keepalive_time: 30
      - net.ipv4.tcp_keepalive_probes: 8
      - net.ipv4.conf.all.arp_accept: 1
      - net.ipv4.tcp_retries2: 5
      - net.bridge.bridge-nf-call-arptables: 1
      - net.bridge.bridge-nf-call-iptables: 1
      - net.bridge.bridge-nf-call-ip6tables: 1
      - net.ipv4.neigh.default.gc_thresh1: 4096
      - net.ipv4.neigh.default.gc_thresh2: 8192
      - net.ipv4.neigh.default.gc_thresh3: 16384
      - net.ipv6.neigh.default.gc_thresh1: 4096
      - net.ipv6.neigh.default.gc_thresh2: 8192
      - net.ipv6.neigh.default.gc_thresh3: 16384
      - net.ipv4.ip_forward: 1
      - net.ipv4.conf.all.arp_filter: 1
      - net.ipv4.conf.all.arp_announce: 2
      - net.ipv4.conf.all.arp_notify: 1
      - net.ipv4.conf.default.log_martians: 0
      - net.ipv4.conf.all.secure_redirects: 0
      - net.ipv4.conf.all.rp_filter: 1
      - net.ipv4.conf.all.accept_source_route: 0
      - net.ipv4.conf.default.secure_redirects: 0
      - net.ipv4.conf.all.accept_redirects: 0
      - net.ipv4.conf.default.rp_filter: 1
      - net.ipv4.conf.default.accept_source_route: 0
      - net.ipv4.conf.default.accept_redirects: 0
      - net.ipv4.conf.all.log_martians: 0
      - net.ipv6.conf.default.disable_ipv6: 0
      - net.ipv6.conf.all.disable_ipv6: 0
      - net.ipv6.conf.all.accept_redirects: 0
      - net.ipv6.conf.default.accept_redirects: 0
      - vm.max_map_count: 262144
      - net.ipv4.ip_nonlocal_bind: 1
      - net.ipv6.ip_nonlocal_bind: 1
      - net.unix.max_dgram_qlen: 128
      - net.ipv6.conf.default.forwarding: 1
      - net.ipv6.conf.all.forwarding: 1
      - kernel.numa_balancing: 0
  - name: virtual_host_config
    hardeningProfile: default
    kernelBootParameters: audit=1 console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0 rootdelay=90 nomodeset crashkernel=256M transparent_hugepage=never intel_iommu=on iommu=pt nomdmonddf nomdmonisw plymouth.ignore-serial-consoles
    sysctlOptions:
      - fs.aio-max-nr: 1048576
      - net.nf_conntrack_max: 1048576
      - kernel.panic: 60
      - kernel.printk: 1
      - net.ipv4.ip_local_reserved_ports: 35357,41055-41056,49000-49001,49152-49215,55572,58882
      - vm.swappiness: 10
      - net.ipv4.conf.default.arp_accept: 1
      - net.core.netdev_max_backlog: 261144
      - net.ipv4.tcp_keepalive_intvl: 3
      - net.ipv4.tcp_keepalive_time: 30
      - net.ipv4.tcp_keepalive_probes: 8
      - net.ipv4.conf.all.arp_accept: 1
      - net.ipv4.tcp_retries2: 5
      - net.bridge.bridge-nf-call-arptables: 1
      - net.bridge.bridge-nf-call-iptables: 1
      - net.bridge.bridge-nf-call-ip6tables: 1
      - net.ipv4.neigh.default.gc_thresh1: 4096
      - net.ipv4.neigh.default.gc_thresh2: 8192
      - net.ipv4.neigh.default.gc_thresh3: 16384
      - net.ipv6.neigh.default.gc_thresh1: 4096
      - net.ipv6.neigh.default.gc_thresh2: 8192
      - net.ipv6.neigh.default.gc_thresh3: 16384
      - net.ipv4.ip_forward: 1
      - net.ipv4.conf.all.arp_filter: 1
      - net.ipv4.conf.all.arp_announce: 2
      - net.ipv4.conf.all.arp_notify: 1
      - net.ipv4.conf.default.log_martians: 0
      - net.ipv4.conf.all.secure_redirects: 0
      - net.ipv4.conf.all.rp_filter: 1
      - net.ipv4.conf.all.accept_source_route: 0
      - net.ipv4.conf.default.secure_redirects: 0
      - net.ipv4.conf.all.accept_redirects: 0
      - net.ipv4.conf.default.rp_filter: 1
      - net.ipv4.conf.default.accept_source_route: 0
      - net.ipv4.conf.default.accept_redirects: 0
      - net.ipv4.conf.all.log_martians: 0
      - net.ipv6.conf.default.disable_ipv6: 0
      - net.ipv6.conf.all.disable_ipv6: 0
      - net.ipv6.conf.all.accept_redirects: 0
      - net.ipv6.conf.default.accept_redirects: 0
      - vm.max_map_count: 262144
      - net.ipv4.ip_nonlocal_bind: 1
      - net.ipv6.ip_nonlocal_bind: 1
      - net.unix.max_dgram_qlen: 128
      - net.ipv6.conf.default.forwarding: 1
      - net.ipv6.conf.all.forwarding: 1
      - kernel.numa_balancing: 0
  - name: control_host_config
    hardeningProfile: default
    cpuScalingGovernor: performance
    lldp:
      enabled: False
      msgTxInterval: 30
      msgTxHold: 4
    kernelBootParameters: audit=1 console=tty0 console=ttyS0,115200 net.ifnames=0 biosdevname=0 rootdelay=90 nomodeset crashkernel=256M transparent_hugepage=never intel_iommu=on iommu=pt nomdmonddf nomdmonisw plymouth.ignore-serial-consoles
    sysctlOptions:
      - fs.aio-max-nr: 1048576
      - fs.inotify.max_user_instances: 4096
      - net.nf_conntrack_max: 1048576
      - kernel.panic: 60
      - kernel.printk: 1
      - net.ipv4.ip_local_reserved_ports: 35357,41055-41056,49000-49001,49152-49215,55572,58882
      - vm.swappiness: 10
      - net.ipv4.conf.default.arp_accept: 1
      - net.core.netdev_max_backlog: 261144
      - net.ipv4.tcp_keepalive_intvl: 3
      - net.ipv4.tcp_keepalive_time: 30
      - net.ipv4.tcp_keepalive_probes: 8
      - net.ipv4.conf.all.arp_accept: 1
      - net.ipv4.tcp_retries2: 5
      - net.bridge.bridge-nf-call-arptables: 1
      - net.bridge.bridge-nf-call-iptables: 1
      - net.bridge.bridge-nf-call-ip6tables: 1
      - net.ipv4.neigh.default.gc_thresh1: 4096
      - net.ipv4.neigh.default.gc_thresh2: 8192
      - net.ipv4.neigh.default.gc_thresh3: 16384
      - net.ipv6.neigh.default.gc_thresh1: 4096
      - net.ipv6.neigh.default.gc_thresh2: 8192
      - net.ipv6.neigh.default.gc_thresh3: 16384
      - net.ipv4.ip_forward: 1
      - net.ipv4.conf.all.arp_filter: 1
      - net.ipv4.conf.all.arp_announce: 2
      - net.ipv4.conf.all.arp_notify: 1
      - net.ipv4.conf.default.log_martians: 0
      - net.ipv4.conf.all.secure_redirects: 0
      - net.ipv4.conf.all.rp_filter: 1
      - net.ipv4.conf.all.accept_source_route: 0
      - net.ipv4.conf.default.secure_redirects: 0
      - net.ipv4.conf.all.accept_redirects: 0
      - net.ipv4.conf.default.rp_filter: 1
      - net.ipv4.conf.default.accept_source_route: 0
      - net.ipv4.conf.default.accept_redirects: 0
      - net.ipv4.conf.all.log_martians: 0
      - net.ipv6.conf.default.disable_ipv6: 0
      - net.ipv6.conf.all.disable_ipv6: 0
      - net.ipv6.conf.all.accept_redirects: 0
      - net.ipv6.conf.default.accept_redirects: 0
      - vm.max_map_count: 262144
      - net.ipv4.ip_nonlocal_bind: 1
      - net.ipv6.ip_nonlocal_bind: 1
      - net.unix.max_dgram_qlen: 128
      - net.ipv6.conf.default.forwarding: 1
      - net.ipv6.conf.all.forwarding: 1
      - kernel.numa_balancing: 0
...
