#
# Configuration file with the memory assignments
#
---
memoryAssignments:
  - name: controller_memory
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 40
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 16
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 1024
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_qemu_1G
        owner: libvirt
        count: 56

  - name: compute_r640_memory
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 175
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 175
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 350
  - name: compute_r740_memory
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 80
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 80
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 160

  - name: compute_r740_vxsds_memory
    defaultHugePageSize: 1G
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 160
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 160
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_nova_1G
        owner: libvirt
        count: 320


  - name: vxsds_memory
    hugepagesAssignments:
      - name: numa0_2mb
        size: 2M
        count: 1024
        numaNode: 0
      - name: numa1_2mb
        size: 2M
        count: 1024
        numaNode: 1
      - name: numa0_1gb
        size: 1G
        count: 20
        numaNode: 0
      - name: numa1_1gb
        size: 1G
        count: 20
        numaNode: 1
    hugepagesMountpoint:
      - name: mount_2mb
        size: 2M
        mountpoint: /mnt/huge_ovs_2M
        owner: ovs
        count: 2048
      - name: mount_1gb
        size: 1G
        mountpoint: /mnt/huge_qemu_1G
        owner: libvirt
        count: 40
...
