#######################################################################################
##  Configuration file with CEE network link topology information                     #
#######################################################################################
##
#######################################################################################
---
networkLinks:
...
