vnflcm:
  vnfInstanceName: vpod2-pcg1
  vnfProductName: PCG
  #csar-file: /lab/pccc_builds/images/PCG/PCG_1.23/PCG_1.23_EP1_T-153595/PCG_CXP9041656_1-R58C234.csar
  vnfSoftwareVersion: CXP9041656_1.R58C
  #vnfdId: 4d2ac831-960c-47e3-9b6f-efe88005a02d
  instantiate-file: instantiate.json
  values-file: values.yaml
  clusterName: n182-eccd2
  namespace: pcg
access-info:
  oam: pcg1-n182-vpod2.seli.gic.ericsson.se
  ldap-admin:
    user: sysadmin
    pass: c3lzQWRtMW5ARGF5MA==
  users:
  - user: pcg-admin
    pass: RG01R0NAUzBsdXQhb24=
    pass-init: Q2hhbmdlbWVAMXN0
pipeline:
- module: create-namespace
- module: create-k8s-secret
  name: eric-pc-gateway-ldap-server-secret
  sources:
  - type: literal
    key: adminuser
    value: sysadmin
  - type: literal
    key: passwd
    value: sysAdm1n@Day0
  - type: literal
    key: adminpasswd
    value: $6$fzLPYlRZCpweJMJC$AiNfP0WYE3npY8Za6GxMFoGj75TOl.TS6tmnnky2Bv5wY0Ek8RIoJlr9pyj0LF3wMMaNsNTUH4jp2lIHviJGS0
- module: create-k8s-secret
  name: eric-pc-gateway-snmp-alarm-provider-config
  sources:
  - type: file
    key: snmp-alarm-provider-config
    file: snmp-config.json
- module: instantiate
- module: verify-pod-running
  ignore-not-running:
  - eric-data-search-engine-curator
- module: run-k8s-command
  name: Patching daemonset eric-log-shipper to tolerate high-throughput taint
  cmd: patch daemonsets eric-log-shipper -p '{"spec":{"template":{"spec":{"tolerations":[{"effect":"NoSchedule","key":"high-throughput","operator":"Equal","value":"true"}]}}}}'
- module: verify-pod-ready
  check-interval: 5
  daemonsets:
  - eric-log-shipper
- module: run-k8s-command
  name: Allow PM server to use non-tls port 9090
  cmd: patch svc eric-pm-server --type=json -p '[{"op":"add","path":"/spec/ports/-","value":{"name":"http-pm","port":9090,"protocol":"TCP","targetPort":http-pm}}]'
- module: run-k8s-command
  name: Create networkpolicy to allow accessing eric-pm-server and eric-data-search-engine
  cmd: |
    apply -f {file1}
    apply -f {file2}
  inline-files:
    file1: network-policy/eric-pm-server-allow.yaml
    file2: network-policy/eric-data-search-engine-allow.yaml
- module: run-k8s-command
  name: Create pm server ingress
  cmd: create ingress eric-pm-server --rule="eric-pm-server-pcg1.ingress.node182-cluster2.seli.gic.ericsson.se/*=eric-pm-server:9090"
- module: verify-pod-ready
  check-interval: 5
  deployments:
  - eric-cm-yang-provider
- module: sleep
  duration: 30
- module: load-cmyp-user-config
  file: user-config.txt
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 30
- module: change-initial-password
- module: load-cmyp-app-config
  file: pcg-config.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
- module: load-cmyp-app-config
  file: ddc-config.txt
  user-id: 0
  proto: ssh
  retry-interval: 30
- module: sleep
  duration: 10
