######################################
## CNF general information
######################################
nodeName: pod56-ccsm1
nodeType: CCSM
instance: ""
systemProfile: standard

vnflcm:
  clusterName: pod56-eccd1
  namespace: ccsm
users:
  day1:
  - username: ccsm-admin
    password: Changeme@1st
    groups:
    - ausf_admin
    - udm_sensitive_key_admin
    - udm_admin
    - system-admin
    - nrfagent-admin
    - hssepc_admin
    - ccsm-admin
    - eir_admin
  - username: ccsm-sec
    password: Changeme@1st
    groups:
    - udm_security_admin
    - nrfagent-security-admin
    - system-security-admin

license:
  customerId: "946060"
  swltId: STA-CCSM-12

cnom:
  fqdn: cnom.ccsm.pod56-eccd1.seln.ete.ericsson.se

snmp:
  agentEngineId: 8000137001C0A856ECCD107E28
  sourceIdentifier: 10.130.34.226

ddc:
  remotePath: ddc/eccd1/pod56-ccsm1

######################################
## CNF specific information
######################################
ccsm:
  ausf:
    instanceId: 76f4b62e-f3f7-454e-9562-56eccd1d0793
    host: ausf1.pod56
    port: 443
  udm:
    instanceId: 841d1b7c-5103-11e9-8c09-56eccd107e28
    host: udm1.pod56
    port: 443
  eir:
    instanceId: 77fba27d-6a44-4074-8d9a-56eccd1fc6ef
    host: eir1.pod56
    port: 443
  hss:
    instanceId: 9448c0d3-6590-4e54-b90f-56eccd1fc48d
    host: hss1.pod56
    port: 80
    diameter:
      host: esm

######################################
## CNF certificates specific
######################################
certs:
  iccr-external-tls-certificate:
    p12: ../../../certs/pod56-eccd1/ccsm/ccsm-iccr-server.p12
  eric-ccsm-sbi-server-certs:
    p12: ../../../certs/pod56-eccd1/ccsm/ccsm-sbi-server.p12
  eric-ccsm-sbi-client-certs:
    p12: ../../../certs/pod56-eccd1/ccsm/ccsm-sbi-client.p12

######################################
## CNF dimensioning specific
######################################
hpaReplica:
  eric-udm-cancelepclocation: {min: 2, max: 2}
  eric-udm-capacity: {min: 1, max: 20}
  eric-udm-eapauth: {min: 2, max: 2}
  eric-udm-eapprimeauth: {min: 2, max: 2}
  eric-udm-epsauth: {min: 5, max: 5}
  eric-udm-gbaauth: {min: 2, max: 2}
  eric-udm-imsauth: {min: 2, max: 2}
  eric-udm-iratamfdereg: {min: 2, max: 3}
  eric-udm-iratamflocation: {min: 2, max: 2}
  eric-udm-iratsndereg: {min: 2, max: 3}
  eric-udm-iwk5g2g: {min: 2, max: 2}
  eric-udm-sdmamdata: {min: 2, max: 2}
  eric-udm-sdmimplicitunsub: {min: 3, max: 4}
  eric-udm-sdmmultipledataset: {min: 3, max: 4}
  eric-udm-sdmnotif: {min: 2, max: 2}
  eric-udm-sdmnssai: {min: 2, max: 2}
  eric-udm-sdmsmdata: {min: 2, max: 3}
  eric-udm-sdmsmfselect: {min: 2, max: 2}
  eric-udm-sdmsubscriptions: {min: 5, max: 5}
  eric-udm-sdmuectxtsmf: {min: 2, max: 2}
  eric-udm-ueauth: {min: 3, max: 3}
  eric-udm-uecmamfget: {min: 2, max: 2}
  eric-udm-uecmamfderegnotifier: {min: 3, max: 3}
  eric-udm-uecmamfregupdate: {min: 2, max: 2}
  eric-udm-uecmreg: {min: 4, max: 5}
  eric-udm-uecmsmfderegistration: {min: 2, max: 2}
  eric-udm-uecmsmfregistration: {min: 3, max: 4}
  eric-ausf-capacity: {min: 2, max: 20}
  eric-ausf-engine: {min: 2, max: 2}
  eric-eir-eireic: {min: 5, max: 6}
  eric-eir-s13diameter: {min: 2, max: 2}
  eric-eir-diametereireic: {min: 2, max: 2}
  eric-hssepc-capacity: {min: 1, max: 20}
  eric-hssepc-s6adiameter: {min: 2, max: 2}
  eric-hssepc-iratsndereg: {min: 4, max: 5}
  eric-hssepc-s6aauthentication: {min: 5, max: 6}
  eric-hssepc-s6acancellocation: {min: 4, max: 5}
  eric-hssepc-s6adeletesubscriber: {min: 2, max: 2}
  eric-hssepc-s6ainsertsubscriber: {min: 2, max: 2}
  eric-hssepc-s6anotify: {min: 2, max: 2}
  eric-hssepc-s6apurge: {min: 2, max: 2}
  eric-hssepc-s6aupdatelocation: {min: 6, max: 7}
  eric-hssepc-soap: {min: 2, max: 2}
  eric-hssepc-subscriptionupdate: {min: 2, max: 2}