global:
  timezone: CET
  pullSecret: regcred
  registry:
    url: container-registry.ingress.pod56-eccd1.seln.ete.ericsson.se
  ericsson:
    licensing:
      licenseDomains:
        - productType: PACKET_CORE_CONTROLLER
          customerId: 946060
          swltId: STA-PCC-9
  licensing:
    sites:
      - hostname: nelsaas-vnf1-thrift.sero.gic.ericsson.se


  sm:
    pgw:
      enabled: true
    sgw:
      enabled: true
    smf:
      enabled: true

snmp-alarm-provider-secret-creation:
  enabled: false

eric-pc-routing-engine:
  interfaces:
    type: macvlan
    macvlan:
      - master: eth4

eric-pc-mm:
  eric-pc-mm-controller:
    service:
      useK8sNwSBI: true
    nodeSelector:
      pcc-mm-pod: controller
    securityContext:
      appArmorProfile: docker-pcc
    
  eric-pc-mm-forwarder:
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 2
    ipv6: false
    networks:
    - ipam: {}
      master: eth4
      mtu: 2090
      name: ext1
      type: macvlan
    securityContext:
      appArmorProfile: docker-pcc

  eric-pc-mm-mobility:
    service:
      useK8sNwSBI: true
      sbi:
        type: LoadBalancer
        externalIPv4:
          enabled: true
          loadBalancerIP: 5.8.6.9
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 2
    securityContext:
      appArmorProfile: docker-pcc

  eric-pc-mm-sctp:
    nodeSelector:
      pcc-mm-pod: non-controller
    replicaCount: 2
    securityContext:
      appArmorProfile: docker-pcc

  eric-pc-mm-br-agent:
    nodeSelector:
      pcc-mm-pod: non-controller

eric-pc-sm:
  eric-pc-sm-diameter:
    nodeSelector:
      pcc-sm-pod: non-controller
  eric-pc-sm-http-client:
    nodeSelector:
      pcc-sm-pod: non-controller
    replicaCount: 2
  eric-pc-sm-ip-allocator:
    nodeSelector:
      pcc-sm-pod: non-controller
  eric-pc-sm-controller:
    nodeSelector:
      pcc-sm-pod: controller

  eric-pc-sm-notification-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    annotations:
      metallb.universe.tf/address-pool: pcc-smf-notification
      metallb.universe.tf/allow-shared-ip: pcc-smf-notification

  eric-pc-sm-nsmf-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    services:
      nsmf:
        loadBalancerIP: 5.8.6.1
    replicaCount: 2

  eric-pc-sm-smf-pgw-session:
    replicaCount: 2
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-sgw-session:
    replicaCount: 2
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-br-agent:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-target-database-master-rd:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-target-database-replica-rd:
    nodeSelector:
      pcc-sm-pod: non-controller

  eric-pc-sm-udp-forwarder:
    nodeSelector:
      pcc-sm-pod: non-controller
    replicaCount: 2

eric-pc-vpn-gateway-forwarder:
  replicaCount: 2
  interfaces:
    - name: net0
      type: macvlan
      hostInterface: eth4


eric-pc-kvdb-rd-server:
  numberOfMaster: 3

cnom-loadBalancer-service:
  enabled: true
  annotations:
    metallb.universe.tf/address-pool: pcc-oam
    metallb.universe.tf/allow-shared-ip: pcc-oam

# Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
eric-pc-pm-init:
  resources:
    pmInit:
      limits:
        cpu: 50m

# Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
eric-pm-resource-monitor:
  resources:
    pmrm:
      requests:
        memory: 128Mi

eric-cloud-native-base:

  eric-si-application-sys-info-handler:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      eric-si-application-sys-info-handler:
        requests:
          memory: 100Mi
    asih:
      applicationId: pod56-pcc1

  # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
  eric-log-transformer:
    jvmHeap: 4096m
    replicaCount: 5
    resources:
      logtransformer:
        limits:
          cpu: '2'
          memory: 6Gi
        requests:
          memory: 6Gi
      metrics:
        requests:
          memory: 128Mi
      tlsproxy:
        requests:
          memory: 128Mi

  eric-odca-diagnostic-data-collector:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      diagnostic-data-collector:
        requests:
          memory: 1Gi
          cpu: 1000m
          ephemeral-storage: 5Gi
        limits:
          memory: 4Gi
          cpu: 1500m
          ephemeral-storage: 20Gi

  eric-pm-server:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    persistentVolume:
      size: 32Gi
    resources:
      eric-pm-exporter:
        requests:
          memory: 64Mi
      eric-pm-server:
        limits:
          memory: 12000Mi
        requests:
          memory: 8000Mi

  eric-sec-key-management:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      metrics:
        requests:
          memory: 50Mi

  eric-cm-mediator:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      eric-cm-mediator:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi

  eric-data-message-bus-kf:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      messagebuskf:
        requests:
          cpu: '2'
          memory: 2Gi

  eric-data-object-storage-mn:
    resources:
      # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
      server:
        limits:
          cpu: 1100m
          memory: 8Gi
        requests:
          cpu: 1100m
          memory: 2Gi

  eric-fh-snmp-alarm-provider:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      alarmprovider:
        limits:
          memory: 1024Mi
    service:
      externalIPv4:
        enabled: true
        annotations:
          sharedVIPLabel: pcc-oam
          addressPoolName: pcc-oam
    sourceIdentifierType: 1
    sourceIdentifier: "10.130.34.233"


  # This is a YAML-formatted file used for dimensioning Search Engine.
  # Declare variables to be passed into your templates at deploy time using
  # “--values <path>/search-engine.medium.yaml” during helm install.

  # Configuration of Search Engine
  # Note that the storage size and numbers of replicas for Search Engine affect the retention mechanism provided by Search Engine Curator
  # Use the deployment variants for Search Engine to guarantee intact functionality
  eric-data-search-engine:
    #
    # Custom parameter to disable modification of sysctl by CNFs
    autoSetRequiredWorkerNodeSysctl: false
    #

    replicaCount:
      data: 3
    persistence:
      data:
        persistentVolumeClaim:
          size: "48Gi"
    jvmHeap:
      data: "2048m"
    resources:
      data:
        limits:
          cpu: "1000m"
          memory: "4Gi"
        requests:
          cpu: "1000m"
          memory: "4Gi"

  # Configuration of Search Engine Curator
  # Contains the retention mechanism for different log planes in numbered actions
  # Use the deployment variants for Search Engine to guarantee intact functionality
  eric-data-search-engine-curator:
    actions: |
      1:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index name), for pc-sm, pc-mm, pc-routing-app
          and vpn-gw-app prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pc-mm-.*|pc-sm-app|pc-routing-app|vpn-gw-app)-log-.*$'
        - filtertype: pattern
          kind: regex
          value: '^pc-mm-(worker-report|list-subscriber-result|gf-imeicheck|n17-pei-check)-log.*$'
          exclude: True
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 7
      2:
        action: delete_indices
        description: >-
          Delete indices older than 60 days (based on index name), for isp log
          prefixed indices. Ignore the error if the filter does not result in
          an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pcc-isp-log|isp-logs).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 60
      3:
        action: delete_indices
        description: >-
          Delete indices older than 24 hours (based on index name), for indices
          that might contain sensitive information.
          Ignore the error if the filter does not result in an actionable list
          of indices(ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^pc-mm-(worker-report|list-subscriber-result|gf-imeicheck|n17-pei-check)-log.*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 1
      4:
        action: delete_indices
        description: >-
          Delete indices older than 30 days (based on index name), for audit log
          and alarm log prefixed indices. Ignore the error if the filter does
          not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-audit-logs|adp-app-alarm-log|adp-app-asi-logs).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 30
      5:
        action: delete_indices
        description: >-
          Delete indices older than 7 days (based on index name), for common service.
          Ignore the error if the filter does not result in an actionable list of
          indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-logs|pcc-kvdbrd-app-log).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 7
      6:
        action: delete_indices
        description: >-
          Delete indices older than 1 days (based on index name), for debug level logs.
          Ignore the error if the filter does not result in an actionable list of
          indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-debug-logs).*$'
        - filtertype: age
          source: field_stats
          direction: older
          field: '@timestamp'
          stats_result: max_value
          unit: days
          unit_count: 1
      7:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for isp log
          prefixed indices. Ignore the error if the filter does not result
          in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(pcc-isp-log|isp-logs).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      8:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for audit log
          and asi(alarm) log prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-audit-logs|adp-app-alarm-log|adp-app-asi-logs).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date
      9:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for common service
          indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-logs|pcc-kvdbrd-app-log|pc-routing-app-log|vpn-gw-app-log).*$'
        - filtertype: space
          disk_space: 55
          use_age: true
          source: creation_date
      10:
        action: delete_indices
        description: >-
          Delete older indices when the total space is greater than upper limit, for debug
          level log prefixed indices. Ignore the error if the filter does not result
          in an actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(adp-app-debug-logs).*$'
        - filtertype: space
          disk_space: 2
          use_age: true
          source: creation_date


eric-cloud-native-nf-additions:

  eric-pm-bulk-reporter:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      bulkreporter:
        requests:
          memory: 200Mi
    env:
      nodeName: pod56-pcc1

  eric-cm-yang-provider:
    # Dimensioning from ADP pods in resources-max-size-pcc.yaml from csar pkg
    resources:
      schemaSynchronizer:
        requests:
          memory: 128Mi
      sshd:
        requests:
          memory: 256Mi
      yangDbAdapter:
        requests:
          memory: 256Mi
    service:
      externalIPv4:
        enabled: true
        annotations:
          sharedVIPLabel: pcc-oam
          addressPoolName: pcc-oam

  eric-data-sftp-server:
    service:
      externalIPv4:
        enabled: true
        annotations:
          sharedVIPLabel: pcc-oam
          addressPoolName: pcc-oam
